name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: leechae0605/kengdori-backend
          stage: main
          yaml: |
            name: keungdori-be
            app: java@17
            options:
              ports: "8080"
              env:
                - name: KAKAO_CLIENT_ID
                  secret: KAKAO_CLIENT_ID
                - name: DB_PASSWORD
                  secret: DB_PASSWORD
                - name: JWT_SECRET
                  secret: JWT_SECRET
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}